version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - HF_TOKEN=${HF_TOKEN}
    restart: unless-stopped

  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - HF_TOKEN=${HF_TOKEN}
    command: streamlit run main.py
    restart: unless-stopped 